alter table public.incidents
add column if not exists resolved_at timestamp,
add column if not exists duration_minutes int;

create table if not exists public.service_resilience_targets (
    target_id bigint generated by default as identity primary key,
    service_id bigint references public.services(service_id),
    sla_target float not null,
    rto_minutes int not null,
    rpo_minutes int not null,
    created_at timestamp default now()
);

create table if not exists public.tolerance_breaches (
    breach_id bigint generated by default as identity primary key,
    incident_id bigint references public.incidents(incident_id),
    service_id bigint references public.services(service_id),
    breach_type text not null,
    duration_minutes int not null,
    threshold_minutes int not null,
    severity text not null,
    created_at timestamp default now()
);

create table if not exists public.resilience_recommendations (
    recommendation_id bigint generated by default as identity primary key,
    incident_id bigint references public.incidents(incident_id),
    service_id bigint references public.services(service_id),
    recommendation_text text not null,
    priority text not null,
    created_at timestamp default now()
);

create table if not exists public.scenario_simulations (
    simulation_id bigint generated by default as identity primary key,
    scenario_name text not null,
    source_service_id bigint references public.services(service_id),
    impacted_services_count int not null,
    estimated_affected_customers int not null,
    estimated_lost_transactions int not null,
    estimated_loss_usd float not null,
    risk_score float not null,
    created_at timestamp default now()
);

create table if not exists public.vendors (
    vendor_id bigint generated by default as identity primary key,
    vendor_name text not null,
    vendor_type text not null,
    criticality_score float default 0,
    risk_level text default 'LOW',
    created_at timestamp default now()
);

create table if not exists public.vendor_dependencies (
    vendor_dependency_id bigint generated by default as identity primary key,
    vendor_id bigint references public.vendors(vendor_id),
    service_id bigint references public.services(service_id),
    dependency_type text not null,
    created_at timestamp default now()
);

create table if not exists public.advanced_resilience_kpis (
    kpi_id bigint generated by default as identity primary key,
    mttr_minutes float not null,
    mttd_minutes float not null,
    mtbf_minutes float not null,
    sla_compliance_rate float not null,
    open_incident_rate float not null,
    critical_incident_rate float not null,
    created_at timestamp default now()
);

alter table public.resilience_score
add column if not exists unresolved_incidents int,
add column if not exists avg_incident_duration_minutes float,
add column if not exists sla_breaches int,
add column if not exists rto_breaches int,
add column if not exists propagation_count int;

insert into public.service_resilience_targets (service_id, sla_target, rto_minutes, rpo_minutes)
select service_id, 99.95, 15, 5 from public.services where service_name = 'Payment API'
and not exists (select 1 from public.service_resilience_targets t where t.service_id = services.service_id);

insert into public.service_resilience_targets (service_id, sla_target, rto_minutes, rpo_minutes)
select service_id, 99.99, 10, 2 from public.services where service_name = 'Core Banking System'
and not exists (select 1 from public.service_resilience_targets t where t.service_id = services.service_id);

insert into public.service_resilience_targets (service_id, sla_target, rto_minutes, rpo_minutes)
select service_id, 99.90, 30, 15 from public.services where service_name = 'Cloud Provider'
and not exists (select 1 from public.service_resilience_targets t where t.service_id = services.service_id);

insert into public.service_resilience_targets (service_id, sla_target, rto_minutes, rpo_minutes)
select service_id, 99.95, 20, 5 from public.services where service_name = 'Login Service'
and not exists (select 1 from public.service_resilience_targets t where t.service_id = services.service_id);

insert into public.service_resilience_targets (service_id, sla_target, rto_minutes, rpo_minutes)
select service_id, 99.95, 20, 5 from public.services where service_name = 'Customer Database'
and not exists (select 1 from public.service_resilience_targets t where t.service_id = services.service_id);

insert into public.service_resilience_targets (service_id, sla_target, rto_minutes, rpo_minutes)
select service_id, 99.95, 15, 5 from public.services where service_name = 'Transaction Database'
and not exists (select 1 from public.service_resilience_targets t where t.service_id = services.service_id);

insert into public.vendors (vendor_name, vendor_type, criticality_score, risk_level)
select 'AWS', 'CLOUD', 0, 'LOW'
where not exists (select 1 from public.vendors where vendor_name = 'AWS');

insert into public.vendors (vendor_name, vendor_type, criticality_score, risk_level)
select 'Azure', 'CLOUD', 0, 'LOW'
where not exists (select 1 from public.vendors where vendor_name = 'Azure');

insert into public.vendors (vendor_name, vendor_type, criticality_score, risk_level)
select 'Snowflake', 'DATA_PLATFORM', 0, 'LOW'
where not exists (select 1 from public.vendors where vendor_name = 'Snowflake');

insert into public.vendors (vendor_name, vendor_type, criticality_score, risk_level)
select 'Twilio', 'COMMUNICATIONS', 0, 'LOW'
where not exists (select 1 from public.vendors where vendor_name = 'Twilio');

insert into public.vendors (vendor_name, vendor_type, criticality_score, risk_level)
select 'Datadog', 'MONITORING', 0, 'LOW'
where not exists (select 1 from public.vendors where vendor_name = 'Datadog');

insert into public.vendor_dependencies (vendor_id, service_id, dependency_type)
select v.vendor_id, s.service_id, 'PRIMARY_CLOUD'
from public.vendors v, public.services s
where v.vendor_name = 'AWS'
and s.service_name in ('Cloud Provider', 'Payment API', 'Core Banking System')
and not exists (
    select 1 from public.vendor_dependencies d
    where d.vendor_id = v.vendor_id and d.service_id = s.service_id
);

insert into public.vendor_dependencies (vendor_id, service_id, dependency_type)
select v.vendor_id, s.service_id, 'SECONDARY_CLOUD'
from public.vendors v, public.services s
where v.vendor_name = 'Azure'
and s.service_name in ('Login Service', 'Customer Database')
and not exists (
    select 1 from public.vendor_dependencies d
    where d.vendor_id = v.vendor_id and d.service_id = s.service_id
);

insert into public.vendor_dependencies (vendor_id, service_id, dependency_type)
select v.vendor_id, s.service_id, 'DATA_PLATFORM'
from public.vendors v, public.services s
where v.vendor_name = 'Snowflake'
and s.service_name in ('Transaction Database', 'Customer Database')
and not exists (
    select 1 from public.vendor_dependencies d
    where d.vendor_id = v.vendor_id and d.service_id = s.service_id
);

insert into public.vendor_dependencies (vendor_id, service_id, dependency_type)
select v.vendor_id, s.service_id, 'NOTIFICATIONS'
from public.vendors v, public.services s
where v.vendor_name = 'Twilio'
and s.service_name = 'Notification Service'
and not exists (
    select 1 from public.vendor_dependencies d
    where d.vendor_id = v.vendor_id and d.service_id = s.service_id
);

insert into public.vendor_dependencies (vendor_id, service_id, dependency_type)
select v.vendor_id, s.service_id, 'OBSERVABILITY'
from public.vendors v, public.services s
where v.vendor_name = 'Datadog'
and s.service_name = 'Monitoring System'
and not exists (
    select 1 from public.vendor_dependencies d
    where d.vendor_id = v.vendor_id and d.service_id = s.service_id
);

drop policy if exists "Allow anon select services" on public.services;
drop policy if exists "Allow anon select dependencies" on public.dependencies;
drop policy if exists "Allow anon select service metrics" on public.service_metrics;
drop policy if exists "Allow anon insert service metrics" on public.service_metrics;
drop policy if exists "Allow anon select incidents" on public.incidents;
drop policy if exists "Allow anon insert incidents" on public.incidents;
drop policy if exists "Allow anon update incidents" on public.incidents;
drop policy if exists "Allow anon insert alerts" on public.alerts;
drop policy if exists "Allow anon select business impact" on public.business_impact;
drop policy if exists "Allow anon insert business impact" on public.business_impact;
drop policy if exists "Allow anon select incident propagation" on public.incident_propagation;
drop policy if exists "Allow anon insert incident propagation" on public.incident_propagation;
drop policy if exists "Allow anon select service criticality ranking" on public.service_criticality_ranking;
drop policy if exists "Allow anon insert service criticality ranking" on public.service_criticality_ranking;
drop policy if exists "Allow anon delete service criticality ranking" on public.service_criticality_ranking;
drop policy if exists "Allow anon select root cause analysis" on public.root_cause_analysis;
drop policy if exists "Allow anon insert root cause analysis" on public.root_cause_analysis;
drop policy if exists "Allow anon select resilience score" on public.resilience_score;
drop policy if exists "Allow anon insert resilience score" on public.resilience_score;
drop policy if exists "Allow anon delete resilience score" on public.resilience_score;
drop policy if exists "Allow anon select service resilience targets" on public.service_resilience_targets;
drop policy if exists "Allow anon insert tolerance breaches" on public.tolerance_breaches;
drop policy if exists "Allow anon select tolerance breaches" on public.tolerance_breaches;
drop policy if exists "Allow anon select resilience recommendations" on public.resilience_recommendations;
drop policy if exists "Allow anon insert resilience recommendations" on public.resilience_recommendations;
drop policy if exists "Allow anon select scenario simulations" on public.scenario_simulations;
drop policy if exists "Allow anon insert scenario simulations" on public.scenario_simulations;
drop policy if exists "Allow anon select vendors" on public.vendors;
drop policy if exists "Allow anon update vendors" on public.vendors;
drop policy if exists "Allow anon select vendor dependencies" on public.vendor_dependencies;
drop policy if exists "Allow anon select advanced resilience kpis" on public.advanced_resilience_kpis;
drop policy if exists "Allow anon insert advanced resilience kpis" on public.advanced_resilience_kpis;

create policy "Allow anon select services" on public.services for select to anon using (true);
create policy "Allow anon select dependencies" on public.dependencies for select to anon using (true);
create policy "Allow anon select service metrics" on public.service_metrics for select to anon using (true);
create policy "Allow anon insert service metrics" on public.service_metrics for insert to anon with check (true);
create policy "Allow anon select incidents" on public.incidents for select to anon using (true);
create policy "Allow anon insert incidents" on public.incidents for insert to anon with check (true);
create policy "Allow anon update incidents" on public.incidents for update to anon using (true) with check (true);
create policy "Allow anon insert alerts" on public.alerts for insert to anon with check (true);
create policy "Allow anon select business impact" on public.business_impact for select to anon using (true);
create policy "Allow anon insert business impact" on public.business_impact for insert to anon with check (true);
create policy "Allow anon select incident propagation" on public.incident_propagation for select to anon using (true);
create policy "Allow anon insert incident propagation" on public.incident_propagation for insert to anon with check (true);
create policy "Allow anon select service criticality ranking" on public.service_criticality_ranking for select to anon using (true);
create policy "Allow anon insert service criticality ranking" on public.service_criticality_ranking for insert to anon with check (true);
create policy "Allow anon delete service criticality ranking" on public.service_criticality_ranking for delete to anon using (true);
create policy "Allow anon select root cause analysis" on public.root_cause_analysis for select to anon using (true);
create policy "Allow anon insert root cause analysis" on public.root_cause_analysis for insert to anon with check (true);
create policy "Allow anon select resilience score" on public.resilience_score for select to anon using (true);
create policy "Allow anon insert resilience score" on public.resilience_score for insert to anon with check (true);
create policy "Allow anon delete resilience score" on public.resilience_score for delete to anon using (true);
create policy "Allow anon select service resilience targets" on public.service_resilience_targets for select to anon using (true);
create policy "Allow anon insert tolerance breaches" on public.tolerance_breaches for insert to anon with check (true);
create policy "Allow anon select tolerance breaches" on public.tolerance_breaches for select to anon using (true);
create policy "Allow anon select resilience recommendations" on public.resilience_recommendations for select to anon using (true);
create policy "Allow anon insert resilience recommendations" on public.resilience_recommendations for insert to anon with check (true);
create policy "Allow anon select scenario simulations" on public.scenario_simulations for select to anon using (true);
create policy "Allow anon insert scenario simulations" on public.scenario_simulations for insert to anon with check (true);
create policy "Allow anon select vendors" on public.vendors for select to anon using (true);
create policy "Allow anon update vendors" on public.vendors for update to anon using (true) with check (true);
create policy "Allow anon select vendor dependencies" on public.vendor_dependencies for select to anon using (true);
create policy "Allow anon select advanced resilience kpis" on public.advanced_resilience_kpis for select to anon using (true);
create policy "Allow anon insert advanced resilience kpis" on public.advanced_resilience_kpis for insert to anon with check (true);
